compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "POOLS", id = "0d79b9ad6cd24d12971e2a375681fed6", preview_id = "a3026cd66e41471db5a7c69703458c83"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools", preview_bucket_name = "subgraph-pools-dev" }
]
main = "src/index.ts"
name = "routing-dev"
node_compat = true
[triggers]
crons = ["0 0 * * *"]

[env.production]
kv_namespaces = [
  {binding = "POOLS", id = "0d79b9ad6cd24d12971e2a375681fed6"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools", preview_bucket_name = "subgraph-pools-dev" }
]
name = "routing"
[env.production.triggers]
crons = ["0 0 * * *"]

# - AXIOM_TOKEN
# The necessary secrets are:
# - ETH_NODE
# - GOERLI_NODE
# - BSC_NODE
# - BSC_TESTNET_NODE
# - FDAX_NODE

# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# echo https://mainnet-rpc.5dax.com | wrangler secret put FDAX_NODE
# echo https://eth.llamarpc.com | wrangler secret put ETH_NODE
# echo https://eth-goerli.public.blastapi.io | wrangler secret put GOERLI_NODE
# echo https://bsc-dataseed.binance.org | wrangler secret put BSC_NODE
# echo https://data-seed-prebsc-2-s1.binance.org:8545 | wrangler secret put BSC_TESTNET_NODE
