compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "FARMS", id = "b653f9b8db0a498a928c445275198bee", preview_id = "2c025309922d49db9f5e56b8448dce0e"},
]
main = "src/index.ts"
name = "farms-dev"
node_compat = true
[vars]
FORCE_UPDATE_KEY = "force"
KV_CACHE = false
[triggers]
crons = []

[env.production]
kv_namespaces = [
  {binding = "FARMS", id = "b653f9b8db0a498a928c445275198bee"},
]
name = "farms"
node_compat = true
[env.production.vars]
KV_CACHE = true
[env.production.triggers]
crons = ["0 0 * * *", "*/1 * * * *"]

# The necessary secrets are:
# - ETH_NODE
# - GOERLI_NODE
# - BSC_NODE
# - BSC_TESTNET_NODE
# - FDAX_NODE

# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# echo https://mainnet-rpc.5dax.com | wrangler secret put FDAX_NODE
# echo https://eth.llamarpc.com | wrangler secret put ETH_NODE
# echo https://eth-goerli.public.blastapi.io | wrangler secret put GOERLI_NODE
# echo https://bsc-dataseed.binance.org | wrangler secret put BSC_NODE
# echo https://data-seed-prebsc-2-s1.binance.org:8545 | wrangler secret put BSC_TESTNET_NODE
